### PR TITLE
Add entirely harmless avatar for indigo

### PR DESCRIPTION
**Pull request by bitglue**

### CODE REVIEW

**Comment by sshirokov** [comment]
Too bad I'm gonna transcode that avatar now, because SOMEONE wanted to act clever about it.

**Comment by Drewzar** [comment]
What a story. 👏

**Comment by bitglue** [comment]
ok ok ok fine I made a new one

**Comment by sshirokov** [comment]
Ok, but the new one is illegal

**Comment by bitglue** [comment]
☹️ 

just merge the first 2 commits i guess.

**Pull request closed without merging**
