### PR TITLE
Added a dope avatar.

### PR DESCRIPTION
**Pull request by Sandhage**

### CODE REVIEW

**Comment by BeefKnuckleback** [comment]
The bottom edge of the avatar should touch the bottom of the image.  Looks good otherwise.

**Comment by drobati** [comment]
Ha, dope avatar indeed.

**Comment by sshirokov** [comment]
YES, HELLO, STILL WAITING FOR THE FOLLOW UP COMMIT

0caf7b30cde66c9123f060ac341a5c97bfe32823c03a64f9bafa99d71dfe4785

**Comment by skalnik** [comment]
`.syzyger is dead`

**Comment by sshirokov** [comment]
We'll see if it all burns down, I guess

**Pull request merged**
