### PR TITLE
Add shyguy to the list

### PR DESCRIPTION
**Pull request by skalnik**
Soon, we will all be here.

### CODE REVIEW

**Comment by BeefKnuckleback** [comment]
What would it take to add some kind of handle variation tracking to AYP?  I'm assuming it's possible but very non-trivial.

**Comment by sshirokov** [comment]
> What would it take to add some kind of automated handle variation tracking to AYP?

It wouldn't be hard at all, but it would probably have to be a "blessed" activity to prevent abuse and spam.

**Comment by drobati** [comment]
It would require that hubot-irc-adapter understand nick changes. I looked into this (last year) and there was something missing for that functionality.

**Comment by BeefKnuckleback** [comment]
Is it a conscience?  Sometimes I feel like if we add any more functionality to Hayt he's going to start demanding paid time off.

**Pull request merged**
