### PR TITLE
Hello this is baseball cat

### PR DESCRIPTION
**Pull request by juliamae**
:baseball::cat::juliamae:

### CODE REVIEW

**Comment by Drewzar** [comment]
That _should_ work? :+1:

**Comment by sshirokov** [comment]
This might look weird floating off the ground on most backgrounds. 

@BeefKnuckleback -- :cat: :thought_balloon:

**Comment by juliamae** [comment]
Where do you even see this. My irc client is all text.

**Comment by juliamae** [comment]
oic, it's to make those comics. it's probably fine.

**Comment by BeefKnuckleback** [comment]
Let's see it in action. :+1:

**Pull request merged**
