### PR TITLE
Allow user ███████

### LINKED ISSUE #182: Allow users to redact their own words from AYP with square braces
I was thinking about redactions the other night, and was thinking perhaps if you surround a phrase with square braces we could redact it in AYP. I couldn't think of any real downsides, curious if anyone else does.

cc/ @sshirokov

### PR DESCRIPTION
**Pull request by skalnik**
Fixes #182 with ██████ ███████.

Someone ███ to █████ ██ you █████ █████

cc/ @sshirokov

### CODE REVIEW

**Comment by sshirokov** [comment]
Since our tests are on fire, because we're morons, please link some regex testing sites where I can see this regex be right.

**Comment by skalnik** [comment]
██████ ███ ██ ██ I made you ████:

https://regex101.com/r/aU3lB7/1

**Comment by sshirokov** [comment]
In the PR you have

`\[[^\]*]\]`

In the test page you have

`\[[^\]]*\]`

Why are you trying to hack me?

**Comment by skalnik** [comment]
████ :wrench:

**Pull request merged**
