### PR TITLE
do the thing again but with imgur posts this time

### PR DESCRIPTION
**Pull request by justinwoo**
...you know the thing with the top comment or whatever if its a gallery or something idk

### CODE REVIEW

**Comment by sshirokov** [comment]
IS THIS EVEN STILL A REAL LIFE THING? ARE WE DOING THIS? IS THIS A THING THAT'S BEING DONE?

WHAT'S THE DONE FACTOR HERE?

HOW MANY POINTS IS THIS!?

WHAT IS YOUR VELOCITY!?

HOW MUCH LONGER DO WE ALL HAVE LEFT?

WHAT IS THE DEFINITION OF SELF AWARENESS?

CAN YOU SOLIDLY STATE YOUR BELIEF OR DISBELIEF IN A HIGHER POWER?

WILL WE BE JUDGED FOR OUR THOUGHTS RETROACTIVELY IF THE TECHNOLOGY ALLOWS FOR IT?

WHAT IS THE MOTIVATION OF GOD TO CREATE SUFFERING?

**Comment by sshirokov** [comment]
Dick move, buddy.

**Comment by Drewzar** [comment]
Have we deployed this and tested it?

**Comment by sshirokov** [comment]
We sure haven't, nor do I know if this even works

**Comment by Drewzar** [comment]
Lets deploy it and test it that way \o/ at worst we roll it back and close this PR forever till @justinwoo  comes back from the ded.

**Comment by sshirokov** [comment]
This is awful and it works. :shipit:

**Comment by justinwoo** [comment]
you guys didn't merge this yet???? no wonder our imgur links are broke

**Pull request merged**
