### PR TITLE
Create ROADMAP.md

### PR DESCRIPTION
**Pull request by sbryant**
You know we have priorities

### CODE REVIEW

**Comment by sshirokov** [comment]
You're the worst.

**Comment by skalnik** [comment]
God dammit

**Comment by Drewzar** [comment]
Do we have anyone from product to sign off on this?

**Comment by skalnik** [comment]
Build fails, crap ROADMAP.

**Comment by sshirokov** [comment]
:money_with_wings: :chart_with_upwards_trend: 

:ok_hand:

Can you business the tests into running again?

**Comment by sshirokov** [comment]
@sbryant -- Merge master into this and the tests will pass.

**Pull request merged**
