### PR TITLE
replace the google images script with an external script taht require…

### PR DESCRIPTION
**Pull request by justinwoo**
…s some extra setup to get 100 image searches a day which kind of sucks but what are you gonna do when the only alternative seems to be to write a complicated script to click and scrape image links randomly from some search site's image results or whatnot

SEE https://github.com/hubot-scripts/hubot-google-images#configuration

DOESNT WORK AUTOMAGICALLY

### CODE REVIEW

**Comment by skalnik** [comment]
omg best maintainer 😻

**Comment by BeefKnuckleback** [comment]
:heart_eyes:

**Comment by Drewzar** [comment]
What's the status of this? I'm losing $8k/sec here.

**Comment by sshirokov** [comment]
**Update:** still haven't configured shit. Suckers.

**Comment by sshirokov** [comment]
Feel free to [encourage me](https://www.patreon.com/arrakis) to spend more time working on Hayt :trollface:

**Comment by drobati** [comment]
I (encourage you)[https://www.patreon.com/arrakis?ty=p].

**Comment by drobati** [comment]
http://i.imgur.com/CQeOG3q.png

**Comment by sshirokov** [comment]
nice

**Pull request merged**
